version: 0.2
env:
  variables:
    CF_STACK : "tmp-devops-stack"
    CF_S3_BUCKET : "devops-lambda-artifacts"

phases:
  install:
    commands:
      # Sam 설치
      - curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli-linux-x86_64.zip
      - unzip -qq aws-sam-cli-linux-x86_64.zip -d ./sam-installation
      - sudo ./sam-installation/install
      - sam --version
  pre_build:
    commands:
      - PATH=$PATH:.
      - echo $PATH $CF_STACK $CF_S3_BUCKET
      - echo $AWS_DEFAULT_REGION $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_BUILD_ID
  build:
    commands:
      - echo Build started on `date`
      - cd HelloWorldFunction
      - chmod +x gradlew
      - gradlew jar
      - cd ..
      - printf 'y\n' | sam deploy --template-file template.yaml --s3-bucket $CF_S3_BUCKET --stack-name $CF_STACK --capabilities CAPABILITY_IAM
      - echo Build finished on `date`
cache:
  # Cache maven and Python downloads
  paths:
    - '.gradle/**/*'
    - 'HelloWorldFunction/build/**/*'
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '/root/.m2/**/*'